### PR TITLE
Works when other scripts override document.write

### PR DESCRIPTION
**Pull request by noahadams**
Similar to #150 but for 2.0

### CODE REVIEW

**Comment by johnboxall** [comment]
@noahadams I've tweaked yoru tests, can you review and merge?

**Comment by johnboxall** [comment]
@jansepar for this test to pass on CI, it requires a 'rebuild' of the release JS. Should we change CI to always rebuild... or should I commit the rebuilt release files?

**Comment by jansepar** [comment]
@johnboxall the rebuilt files should be committed.

**Comment by noahadams** [comment]
OK, I like the look of this @johnboxall. I'll resolve fresh master conflicts and get this merged.

**Comment by jansepar** [comment]
:+1:

**Pull request merged**
