### PR TITLE
Apply scroll fix for ios8+ [1.3.1]

### PR DESCRIPTION
**Pull request by haroldtreen**
# ios8+ Scroll Fix

Status: **Ready for Review**

Reviewers: @donnielrt @fractaltheory 
JIRA: [RTM-338](https://mobify.atlassian.net/browse/RTM-338)
## Changes
- Apply scroll fix to ios8+
## Test Drive
- Clone
- `make`
- Switch a projects api to 1.3.1
- Test nothing breaks
- Run `grunt test`

### CODE REVIEW

**Comment by haroldtreen** [comment]
I think this will require an update to client before it is testable. 

Also not sure of what project on 1.3 should be tested.

**Comment by donnielrt** [comment]
Not sure if we actually have any projects deployed using 1.3.

**Comment by donnielrt** [comment]
@jansepar @noahadams should we just roll this into 1.3, if we don't have any projects using 1.3 yet?

**Comment by haroldtreen** [comment]
If we don't have projects on 1.3 why would we ever deploy a project to 1.3? :S

Isn't this all super lega-c?

**Comment by donnielrt** [comment]
@haroldtreen we'd possibly want to upgrade 1.0/1.1 projects to 1.3

**Comment by noahadams** [comment]
hypothetically, a 1.1 project with qa time allocated to ti could safely move to 1.3 by just changing the reference in its project.json, that's never happened int he last year though

**Comment by jansepar** [comment]
Looks like we have one 1.3 project: https://github.com/mobify/outrigger-tablet/blob/master/project.json

**Comment by jansepar** [comment]
The Pokedex told me so :)

https://mobify-pokedex.herokuapp.com/

**Comment by donnielrt** [comment]
@jansepar lol, nice

**Comment by haroldtreen** [comment]
Thanks for catching that @fractaltheory !

**Comment by donnielrt** [comment]
:+1:

**Pull request merged**
