### PR TITLE
IE10 tag fixes

### PR DESCRIPTION
**Pull request by jansepar**
- Fixes bootstrap tag to work in IE10. Done by binding the onload event before the script is attached to the document.
- Changes all examples to point to latest mobify.js build

### CODE REVIEW

**Comment by jansepar** [comment]
References issue #139, thanks to @shogun70 for the bug report and fix suggestion!

**Comment by jansepar** [comment]
@noahadams could you give this a review please?

**Comment by noahadams** [comment]
I couldn't reproduce the original issue, but the examples do indeed appear to work in IE10, FF, Chrome and iOS simulator. I'll give the website a quick once-over int he morning and likely merge this.

**Comment by jansepar** [comment]
@noahadams the issue only appeared when accessing them on cdn.mobify.com, and only after refreshing. These examples are currently deployed there. To reproduce, you will have to deploy the old ones.

**Comment by noahadams** [comment]
:+1:

**Comment by noahadams** [comment]
also, fresh website deployed

**Pull request merged**
