### PR TITLE
base_root.tmpl meta tag fix

### PR DESCRIPTION
**Pull request by KyleYoung**
Corrected the viewport meta tag. (Resloves 5 errors and warnings on iPad and iPhone browsers.)

### CODE REVIEW

**Comment by rrjamie** [comment]
I don't know how ours ended up with semicolons...

Docs:

http://developer.apple.com/library/safari/#documentation/appleapplications/reference/SafariHTMLRef/Articles/MetaTags.html
https://developer.mozilla.org/en/Mobile/Viewport_meta_tag/

Tested on iOS & Android 4.0 (Chrome and Android Browser).

**Comment by jansepar** [comment]
I've talked to @KyleYoung via email - he will also be issuing another pull request on the base.tmpl file. Kyle, you can work off master now, opensource-frlendly is now merged in.

**Comment by johnboxall** [comment]
@rrjamie I do - WP7 didn't support `,` in it's meta tag - since we're not supporting it in this version, I think we're fine.

**Comment by KyleYoung** [comment]
Hi guys; I'll be fixing it in base.tmpl as well, as soon as I'm in post-9-to-5 space...
A user-agent hack for WP7 could be included, if backwards compatibility was a concern?

**Comment by johnboxall** [comment]
@KyleYoung the issue was resolved in the Mango release of Windows Phone - I think what you've introduced is a sane default.

**Comment by rrjamie** [comment]
@KyleYoung I merged your changes in mobify-client for you. Good work.

**Comment by KyleYoung** [comment]
Ah, thanks Ryan

**Pull request merged**
