### PR TITLE
V2.0 - GOLD-883: iOS Scroll Fix V2

### PR DESCRIPTION
**Pull request by jvaill**
Merge checklist:
- [x] Removes the old iOS 8.0 patch
- [x] Adds the new iOS 8.0 patch
- [x] Uses the correct iOS 8.0 regex (that works with the simulator)
- [x] Calls the new patch
- [x] Has a test for the new patch
- [x] Has a test for the iOS 8.0 form sibblings bug
- [x] Test on Saucelabs

### CODE REVIEW

**Comment by MikeKlemarewski** [comment]
Tested out the new regex on android, iOS7, and iOS8. Works!

**Comment by MikeKlemarewski** [comment]
@jvaill refactored!

**Comment by MikeKlemarewski** [comment]
Works on the sim!

**Comment by jansepar** [comment]
Passes on Saucelabs! :+1:

**Pull request merged**
