### PR TITLE
V1.0 - GOLD-883: iOS Scroll Fix V2

### PR DESCRIPTION
**Pull request by MikeKlemarewski**
Merge checklist:
- [x] Removes the old iOS 8.0 patch
- [x] Adds the new iOS 8.0 patch
- [x] Uses the correct iOS 8.0 regex (that works with the simulator)
- [x] Calls the new patch
- [x] Has a test for the new patch
- [x] Has a test for the iOS 8.0 form sibblings bug

Adds patch to fix iOS8 scroll bug

**Status**: _Opened for visibility_

**Reviewers**: @jvaill @jansepar

### CODE REVIEW

**Comment by jvaill** [comment]
So I was trying to figure out why this diff was off.. and then I noticed that the merge pull request button is disabled. @MikeKlemarewski can you merge `1.0` into this?

**Comment by MikeKlemarewski** [comment]
Tested on android, iphone 5 and iphone 6 running 8.0.2. I deem this working!

**Comment by jansepar** [comment]
Just realized CST didn't test 1.0 projects. Let's quickly test lulu before merging this puppy in!

**Comment by jansepar** [comment]
Tested lulu - looks good! :+1: nice checklist btw :)

**Pull request merged**
