### PR TITLE
Fix issue where document.writing out the combo code fails in firefox

### PR DESCRIPTION
**Pull request by tedtate**
- due to uglify mangling our literals.

### CODE REVIEW

**Comment by tedtate** [comment]
@noahadams @rrjamie

**Comment by hallvors** [comment]
Thanks for fixing this, it's one of the issues that breaks Wired.com in Firefox for Android: https://bugzilla.mozilla.org/show_bug.cgi?id=923360#c10
I still haven't fully understood these problems, so if you have hints or debug tips, comments in that bug are welcome!

**Comment by hallvors** [comment]
PS - I hope you can backport this fix to older version too
CC @jansepar

**Comment by jansepar** [comment]
Sorry, this actually fixes the issue in the version Wired is using. It needs to be also added to 2.0 :). I'm making a ticket so that we can address this ASAP.

**Comment by hallvors** [comment]
@jansepar, @rrjamie : when we at Mozilla's site compatibility team find sites with the broken version, I'd like to be able to give specific advice like "please update mobify.js to version x.y or later". Could you let me know what version(s) this fix is shipping in?

(Context: Moz bug 984126)

**Comment by rrjamie** [comment]
Hey Hallvors,

This fix landed in our `mobify-client` build tool in version 0.3.29 (see https://github.com/mobify/mobify-client/blob/master/CHANGELOG).

Users are automatically notified to update when the upload their work to Mobify Cloud, so people generally update quickly (though they will have to rebuild their site and deploy a new build for the fix).

If you notice any issues on a mobify.js powered site on Firefox, don't hesitate to let us know.

**Pull request merged**
