### PR TITLE
Changing usage of $ to Mobify.$ in accordion.js

### PR DESCRIPTION
**Pull request by tedtate**
Fixes issue from https://github.com/mobify/mobifyjs/commit/7cd5497f2fcc88ee2024769998702017af3716cc

@jansepar

### CODE REVIEW

**Comment by jansepar** [comment]
Looks good, I will merge it when my other pull request is merged, and when we are ready to do another release.

**Comment by jansepar** [comment]
And thx for the PR!

**Comment by noahadams** [comment]
looks good, merging this now, Shawn I'll merge your other PR shortly (after I test it)

**Comment by noahadams** [comment]
:+1:

**Pull request merged**
