### PR TITLE
V1.3 bower service apis

### PR DESCRIPTION
**Pull request by jansepar**

### CODE REVIEW

**Comment by jansepar** [comment]
@noahadams couple TODOs from yesterday:
- Let's make sure the tests pass in IE10. They failed yesterday for reals, but I'm pretty sure thats because it was we ran it on IE10 before we upgraded the Zepto submodule.
- We said we might conditionally change the size of the array we generate for older browsers. I'll leave this one up to you for whether or not we actually do it.

**Comment by jansepar** [comment]
@noahadams :+1: pending my comments above, and testing it on a real project. The shim looks good.

**Comment by noahadams** [comment]
@jansepar Things look good testing jazzcat and IR on brides, reviewing IE stuff now

**Comment by noahadams** [comment]
IE is passing tests, rewrote circle.yml to work with the new test infrastructure.

**Comment by noahadams** [comment]
@jansepar Just waiting on a test run at this point, you wanna clicky the green button?

**Comment by jansepar** [comment]
All tests pass on Sauce and locally :) :+1:

**Comment by jansepar** [comment]
Looks like the tests are failing on Circle. Could you have a look into why?

**Comment by noahadams** [comment]
had to add a `git submodule update --init --recursive` rule to circle.yml, things are happy on circle now.

**Pull request merged**
